export const COMMON_DISEASES = [
  "Acne",
  "Acute Bronchitis",
  "Acute Kidney Injury",
  "Allergic Rhinitis",
  "Alzheimer's Disease",
  "Anemia",
  "Angina Pectoris",
  "Anxiety Disorder",
  "Appendicitis",
  "Asthma",
  "Atrial Fibrillation",
  "Bipolar Disorder",
  "Breast Cancer",
  "Cataracts",
  "Celiac Disease",
  "Cellulitis",
  "Chronic Bronchitis",
  "Chronic Kidney Disease",
  "Chronic Obstructive Pulmonary Disease (COPD)",
  "Cirrhosis",
  "Colorectal Cancer",
  "Congestive Heart Failure",
  "Coronary Artery Disease",
  "COVID-19",
  "Crohn's Disease",
  "Cystic Fibrosis",
  "Deep Vein Thrombosis (DVT)",
  "Dementia",
  "Depression",
  "Diabetes Mellitus Type 1",
  "Diabetes Mellitus Type 2",
  "Diverticulitis",
  "Eczema",
  "Endometriosis",
  "Epilepsy",
  "Erectile Dysfunction",
  "Fibromyalgia",
  "Gallstones",
  "Gastroesophageal Reflux Disease (GERD)",
  "Glaucoma",
  "Gout",
  "Hashimoto's Thyroiditis",
  "Heart Attack (Myocardial Infarction)",
  "Hepatitis B",
  "Hepatitis C",
  "Herpes Simplex",
  "Herpes Zoster (Shingles)",
  "HIV/AIDS",
  "Hyperlipidemia (High Cholesterol)",
  "Hypertension (High Blood Pressure)",
  "Hyperthyroidism",
  "Hypothyroidism",
  "Inflammatory Bowel Disease (IBD)",
  "Influenza (Flu)",
  "Insomnia",
  "Irritable Bowel Syndrome (IBS)",
  "Kidney Stones",
  "Leukemia",
  "Lung Cancer",
  "Lupus (Systemic Lupus Erythematosus)",
  "Lyme Disease",
  "Lymphoma",
  "Macular Degeneration",
  "Major Depressive Disorder",
  "Melanoma",
  "Migraine",
  "Multiple Sclerosis (MS)",
  "Myasthenia Gravis",
  "Obesity",
  "Osteoarthritis",
  "Osteoporosis",
  "Ovarian Cyst",
  "Pancreatitis",
  "Parkinson's Disease",
  "Peptic Ulcer Disease",
  "Peripheral Artery Disease",
  "Pneumonia",
  "Polycystic Ovary Syndrome (PCOS)",
  "Prostate Cancer",
  "Psoriasis",
  "Pulmonary Embolism",
  "Rheumatoid Arthritis",
  "Schizophrenia",
  "Sciatica",
  "Sepsis",
  "Sickle Cell Anemia",
  "Sleep Apnea",
  "Stroke (Cerebrovascular Accident)",
  "Syphilis",
  "Systemic Sclerosis (Scleroderma)",
  "Tuberculosis (TB)",
  "Ulcerative Colitis",
  "Urinary Tract Infection (UTI)"
];
